import importlib.util
import numpy as np
import sympy as sym
from types import NoneType
from typing import Any, Callable, Sequence, TypeAlias, TypeVar, overload
from sympy.printing.str import StrPrinter

SizeParam: TypeAlias = sym.Expr | int
SizeMaybe: TypeAlias = SizeParam | None
SizeSeq: TypeAlias = Sequence[SizeParam]
SizeInput: TypeAlias = SizeParam | str

class BufferMap:
    SHARED: int = ...
    DISTINCT: int = ...

class BufferAlign:
    BYTE = ...
    WORD = ...
    DWORD = ...
    QWORD = ...
    CACHE_LINE = ...
    SSE = ...
    AVX = ...
    AVX512 = ...
    PAGE = ...
    HUGE_PAGE_2MB = ...
    HUGE_PAGE_1GB = ...

class NativeTypes:
    POINTER = ...
    POINTERb = ...
    NP_INT = ...
    NP_INTb = ...
    NP_FLOAT = ...
    NP_FLOATb = ...
    NP_BOOL = ...
    NP_BOOLb = ...
    NP_COMPLEX = ...
    NP_COMPLEXb = ...
    NB_INT = ...
    NB_INTb = ...
    NB_FLOAT = ...
    NB_FLOATb = ...
    NB_BOOL = ...
    NB_BOOLb = ...
    NB_COMPLEX = ...
    NB_COMPLEXb = ...
    LP64_I = ...
    LP64_Ib = ...
    ILP64_I = ...
    ILP64_Ib = ...

def aligned_buffer(n_bytes: SizeParam, align: SizeParam = BufferAlign.AVX512) -> np.ndarray: ...
def c_orlen(tgt, mtch: str): ...
def buffer_expr(sy: SizeInput | None, warn: bool = True) -> SizeMaybe: ...
def mk_buff_dict(dc: dict[SizeInput, Any]) -> dict[SizeParam, Any]: ...
def bdict(**kwargs) -> dict[SizeParam, Any]: ...
def buffer_symbols(tgt: SizeInput | Sequence[SizeInput], *rest: SizeInput) -> SizeParam | SizeSeq: ...
def dt_buff_exprs(tgt: SizeInput | Sequence[SizeInput] | None) -> SizeMaybe | SizeSeq: ...
def eval_buff_expr(evt: Any, evd: dict | None = None) -> int: ...
def eval_buff_exprs(evts: SizeSeq, evd: dict[sym.Symbol, int] | None = None) -> Sequence[int]: ...
def numb_syms(prefix: str = "t", start: int = 0): ...
def is_eqn(expr: sym.Expr | SizeSeq | int | object | None) -> bool: ...

class BButil:
    typeref1 = ...
    typeref2 = ...
    @classmethod
    def build_header(cls, bmap, args, kwargs, check_alloc: str | None = "buffer", balign: SizeParam = BufferAlign.PAGE, typebytes: Callable | None = None, ceilref: str | None = None) -> str: ...
    @classmethod
    def add_typeparams(cls, args, kwargs, tbld=None) -> str: ...

    ceilref1 = ...
    @classmethod
    def add_ceildiv(cls, clrf: str | None = None) -> str: ...
    @classmethod
    def add_balloc(cls, alloc_eqn, check_alloc: str = "buffer", alignf: str = "aligned_buffer", balign: SizeParam = BufferAlign.PAGE) -> str: ...

def cse_codereduction(exprs: SizeSeq, prefix: str = "t", optimizations: str = "basic", symbols=...): ...
