import numpy as np
import sympy as sym
from types import NoneType
from typing import Any, Optional, Sequence, TypeAlias, Union, override
from anytree import NodeMixin
from bmap._util import BufferAlign, BufferMap, BuffExprMaybe, DTypeLike, InitOp, ShapeLike, SizeExpr

SymDef: TypeAlias = BuffExprMaybe | Sequence[BuffExprMaybe] | tuple[SizeExpr | None, Sequence[SizeExpr], Sequence[SizeExpr]]

class BaseNode(NodeMixin):
    id: int
    label: Optional[str]
    no_merge: bool
    nbytes: SizeExpr | None
    ofs: Optional[int]
    def __init__(self, name: Optional[Union[str, int, float]] = None, no_merge: bool = False) -> None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, name) -> None: ...
    @name.deleter
    def name(self) -> None: ...
    def gen_call(self, *args: object, **kwargs: object) -> tuple[str | tuple[str, ...] | None, str | int | float | None]: ...
    def sym_def(self) -> SymDef: ...
    @property
    def free_symbols(self) -> set[Any]: ...

class ValueNode(BaseNode):
    def __init__(self, value: int | str | sym.Expr | None, name: Optional[Union[str, int, float]] = None) -> None: ...

    value: BuffExprMaybe
    @property
    def vtype(self) -> type[sym.Expr | NoneType | sym.Symbol | int]: ...
    @override
    def gen_call(self, *args: object, **kwargs: object) -> tuple[str | None, str | int | None]: ...
    @override
    def sym_def(self) -> BuffExprMaybe: ...
    @property
    def free_symbols(self) -> set[Any]: ...

class ArrayNode(BaseNode):
    shape: Sequence[SizeExpr]
    dtype: np.dtype | sym.Expr
    bshape: Sequence[SizeExpr]
    array: Optional[np.ndarray]
    barray: Optional[np.ndarray]
    align_ldim: SizeExpr | Sequence[SizeExpr] | None
    itsize: SizeExpr
    order: str
    init_op: InitOp | None
    def __init__(
        self,
        shape: ShapeLike = (0,),
        dtype: DTypeLike = np.float64,
        order: str = "C",
        init_op: InitOp | None = None,
        name: Optional[Union[str, int, float]] = None,
        align_ldim: ShapeLike | None = None,
    ) -> None: ...
    def mk_array(self, buffer: Optional[np.ndarray] = None, sym_dic: dict[sym.Symbol, int] | None = None) -> np.ndarray: ...
    @property
    def value(self) -> np.ndarray | None: ...
    @staticmethod
    def array_genc(offstr: str, dtstr: str, dmstr: str, ord: str) -> str: ...

    npspec = ...
    def gen_call(self, *args: object, **kwargs: object) -> tuple[str, str]: ...
    def sym_def(self) -> tuple[SizeExpr | None, Sequence[SizeExpr], Sequence[SizeExpr]]: ...
    @property
    def free_symbols(self) -> set[Any]: ...

class ContainerNode(BaseNode):
    rule: int
    align: bool
    aligned_eqns: list[SizeExpr]
    def __init__(self, *children: BaseNode, rule: int = BufferMap.DISTINCT, name: Optional[Union[str, int, float]] = None, no_merge: bool = False, align: bool = True) -> None: ...
    def add(self, *kids: BaseNode) -> ContainerNode: ...
    def insert(self, index, *kids): ...
    def order(self, *indices): ...
    def pop(self, *idxs): ...
    def build_flatmap(self, align: SizeExpr = BufferAlign.AVX512, alignb: SizeExpr = BufferAlign.PAGE, name_join: bool = True, force_merge: bool = False, verbose: bool = False): ...
    @staticmethod
    def s_def(syq: sym.Expr | int | object | None) -> str: ...
    def gen_call(self, *args: object, **kwargs: object) -> tuple[str, None] | tuple[tuple[str, ...], None]: ...
    def sym_def(self): ...
    @property
    def free_symbols(self): ...

ItemNodeT: TypeAlias = ValueNode | ArrayNode
