import numpy as np
import sympy as sym
from numbers import Number
from types import NoneType
from typing import Any, Callable, Sequence, TypeAlias, overload
from sympy.printing.str import StrPrinter

def typeof(*args) -> np.dtype: ...

def rgc(func: Callable[..., Any]) -> Callable[..., Any]: ...
BuffExpr: TypeAlias = sym.Expr | int
BuffExprMaybe: TypeAlias = BuffExpr | None
BuffExprSeq: TypeAlias = Sequence[BuffExpr]
BuffExprTuple: TypeAlias = tuple[BuffExprMaybe, ...]
SizeExpr: TypeAlias = int | sym.Expr
SizeSpec: TypeAlias = SizeExpr | str
ShapeLike: TypeAlias = SizeSpec | Sequence[SizeSpec]
InitOp: TypeAlias = int | float | np.ndarray | Callable[[np.ndarray], Any]
DTypeLike: TypeAlias = np.dtype | np.generic | type[np.generic] | sym.Expr | str | int | type[Number] | type[int]
CD_ = ...
FD_ = ...
CD_FUNC: sym.Function = ...
FD_FUNC: sym.Function = ...
use_other = ...
_ESET = ...
HAS_SYM = ...
_GB_EXPR = ...
NT = NoneType

def gen_max(sq: Sequence[SizeExpr], simplify: bool = True) -> sym.Max | int: ...
def gen_add(sq: Sequence[SizeExpr], simplify: bool = True) -> sym.Expr | int: ...
def roundup(var: SizeExpr, rup: SizeExpr | int | None): ...

class GenPrinter(StrPrinter): ...

_gpr = ...

def gen_str(expr) -> str: ...

class BufferMap:
    SHARED: int = ...
    DISTINCT: int = ...

class BufferAlign:
    BYTE = ...
    WORD = ...
    DWORD = ...
    QWORD = ...
    CACHE_LINE = ...
    SSE = ...
    AVX = ...
    AVX512 = ...
    PAGE = ...
    HUGE_PAGE_2MB = ...
    HUGE_PAGE_1GB = ...

class NativeTypes:
    POINTER = ...
    POINTERb = ...
    NP_INT = ...
    NP_INTb = ...
    NP_FLOAT = ...
    NP_FLOATb = ...
    NP_BOOL = ...
    NP_BOOLb = ...
    NP_COMPLEX = ...
    NP_COMPLEXb = ...
    NB_INT = ...
    NB_INTb = ...
    NB_FLOAT = ...
    NB_FLOATb = ...
    NB_BOOL = ...
    NB_BOOLb = ...
    NB_COMPLEX = ...
    NB_COMPLEXb = ...
    LP64_I = ...
    LP64_Ib = ...
    ILP64_I = ...
    ILP64_Ib = ...

class _IDGen:
    _ctr = ...
    @classmethod
    def new_id(cls) -> int: ...

@rgc
def aligned_buffer(n_bytes: int, align: int = BufferAlign.AVX512) -> np.ndarray: ...

_SYMCACHE: dict[str, sym.Expr] = ...
_CHKEQ = ...

def check_eqstr(st: str) -> bool: ...
def c_orlen(tgt, mtch: str): ...
def buffer_expr(sy: int | str | sym.Expr | None, warn: bool = True, safe: bool = True) -> BuffExprMaybe: ...
def mk_buff_dict(dc): ...
def bdict(**kwargs): ...
@overload
def buffer_symbols(*tgt: str) -> tuple[sym.Symbol, ...]: ...
@overload
def buffer_symbols(*tgt: object) -> BuffExprMaybe | tuple[BuffExprMaybe, ...]: ...
def buffer_symbols(*tgt: object) -> BuffExprMaybe | tuple[BuffExprMaybe, ...]: ...
@overload
def dt_buff_exprs(tgt: Sequence[object]) -> tuple[BuffExprMaybe, ...]: ...
@overload
def dt_buff_exprs(tgt: object) -> BuffExprMaybe: ...
def dt_buff_exprs(tgt) -> BuffExprMaybe | tuple[BuffExprMaybe, ...]: ...
def eval_buff_expr(evt: Any, evd: dict | None = None) -> int: ...
def eval_buff_exprs(evts: Sequence[BuffExpr], evd: dict | None = None) -> tuple[int, ...] | Sequence[BuffExpr]: ...
def cf_plcsym(exprs: Sequence[sym.Expr], cd: sym.Function = ..., fd: sym.Function = ...) -> list[sym.Expr]: ...
def numb_syms(prefix: str = "t", start: int = 0): ...
def is_eqn(expr) -> bool: ...

class BButil:
    typeref1 = ...
    typeref2 = ...
    @classmethod
    def build_header(cls, bmap, args, kwargs, check_alloc: str | None = "buffer", balign: SizeExpr = BufferAlign.PAGE, typebytes: Callable | None = None, ceilref: str | None = None) -> str: ...
    @classmethod
    def add_typeparams(cls, args, kwargs, tbld=None) -> str: ...

    ceilref1 = ...
    @classmethod
    def add_ceildiv(cls, clrf: str | None = None) -> str: ...
    @classmethod
    def add_balloc(cls, alloc_eqn, check_alloc: str = "buffer", alignf: str = "aligned_buffer", balign: SizeExpr = BufferAlign.PAGE) -> str: ...

def ls_layers(layers) -> list[str]: ...
def lyr_str_key(lyr: str) -> int: ...
def post_process_cse(repls, reduced, symbols, oneassign_del=True, clean_order=True): ...
def cse_codereduction(exprs: Sequence[sym.Expr], prefix: str = "t", optimizations: str = "basic", symbols=...): ...
def dtype_abbr(dtype: np.dtype) -> str: ...
